version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chinni81/app:1.0 # Tag the image for Docker Hub
    ports:
      - "5000:5000" # Map Flask app to localhost:5000
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://test_user:test_user_password@db/taskdb
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    ports:
      - "3306:3306" # Map MySQL database to localhost:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: taskdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_user_password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck: # Ensure MySQL is ready before Flask app starts
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: chinni81/test:1.0 # Tag the image for Docker Hub
    command: pytest  # Run the tests on startup
    depends_on:
      - app
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///test.db  # Use SQLite for testing
      - PYTHONPATH=/app # Ensure Python looks in the root of the project
    volumes:
      - .:/app  # Mount the entire project folder to /app inside the container
    working_dir: /app  # Set the working directory for the test container
    
volumes:
  db_data: